baseURL = 'http://blog.nightcord.org/'
languageCode = 'zh-CN'
title = 'a8ec29b'
theme = 'ananke'

[params]
  background_color_class = "bg-grey"
  description = "a8ec29b"
  body_classes = "avenir bg-dark-gray"
  text_color = "white"
